//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBManagePositions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LegColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LegColumnWidths"]));
            }
            set {
                this["LegColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TradeColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TradeColumnWidths"]));
            }
            set {
                this["TradeColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CloseTradeColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CloseTradeColumnWidths"]));
            }
            set {
                this["CloseTradeColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BestStrangleColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BestStrangleColumnWidths"]));
            }
            set {
                this["BestStrangleColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int BestStrangleDaysToExpire {
            get {
                return ((int)(this["BestStrangleDaysToExpire"]));
            }
            set {
                this["BestStrangleDaysToExpire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BestStrangleIncludeWeeklies {
            get {
                return ((bool)(this["BestStrangleIncludeWeeklies"]));
            }
            set {
                this["BestStrangleIncludeWeeklies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double BestStrangleTargetITM {
            get {
                return ((double)(this["BestStrangleTargetITM"]));
            }
            set {
                this["BestStrangleTargetITM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int BestStrangleTargetMargin {
            get {
                return ((int)(this["BestStrangleTargetMargin"]));
            }
            set {
                this["BestStrangleTargetMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OpenTradeColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenTradeColumnWidths"]));
            }
            set {
                this["OpenTradeColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int FormWidth {
            get {
                return ((int)(this["FormWidth"]));
            }
            set {
                this["FormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("668")]
        public int FormHeight {
            get {
                return ((int)(this["FormHeight"]));
            }
            set {
                this["FormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IfUsingIBGateway {
            get {
                return ((bool)(this["IfUsingIBGateway"]));
            }
            set {
                this["IfUsingIBGateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IfUsingInteractiveBrokers {
            get {
                return ((bool)(this["IfUsingInteractiveBrokers"]));
            }
            set {
                this["IfUsingInteractiveBrokers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IfUsingTDI {
            get {
                return ((bool)(this["IfUsingTDI"]));
            }
            set {
                this["IfUsingTDI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ClientID {
            get {
                return ((int)(this["ClientID"]));
            }
            set {
                this["ClientID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Finance\\Logs\\")]
        public string LogDir {
            get {
                return ((string)(this["LogDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=E:\\Finance\\Database\\options.m" +
            "df;Initial Catalog=Options;Integrated Security=True")]
        public string optionsConnectionString {
            get {
                return ((string)(this["optionsConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290")]
        public int SplitDistance {
            get {
                return ((int)(this["SplitDistance"]));
            }
            set {
                this["SplitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>100</string>
  <string>100</string>
  <string>100</string>
  <string>100</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BetaColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BetaColumnWidths"]));
            }
            set {
                this["BetaColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n  <string>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IBColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IBColumnWidths"]));
            }
            set {
                this["IBColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>200</string>\r\n  <string>200</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LocalColumnWidths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LocalColumnWidths"]));
            }
            set {
                this["LocalColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IfUsingCore {
            get {
                return ((bool)(this["IfUsingCore"]));
            }
            set {
                this["IfUsingCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/03/2016 09:39:00")]
        public global::System.DateTime RememberDateExpiry {
            get {
                return ((global::System.DateTime)(this["RememberDateExpiry"]));
            }
            set {
                this["RememberDateExpiry"] = value;
            }
        }
    }
}
